siteTitle: "Red Hat"
projectTitle: "RPM-Importer"
title: "RPM Dist-Git Importer"
owner: "Red Hat"
ownerEmail: ncross@redhat.com

markdown: kramdown
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

theme: jekyll-theme-slate
