name: Java CI with Maven

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]
    paths-ignore: ["LICENSE", "README.md"]

jobs:
  call-maven-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@646d9b629925d6405fb06ed1476aefd6b2cdca86 # v0.0.23
    with:
      build_command: "mvn -B -V install -Dvalidate-format"
      upload_artifacts: true
