name: Java CI with Maven

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]
    paths-ignore: ["LICENSE", "README.md"]

jobs:
  call-maven-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@b31335d128fec7e29305eeea0b5dc7221829e1a4 # main
    with:
      build_command: "mvn -B -V install -Dvalidate-format"
      upload_artifacts: true
