name: Java CI with Maven

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]
    paths-ignore: ["LICENSE", "README.md"]

jobs:
  call-maven-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@c32f5377788ce8ee9dd823babd583c2dd18604da # v0.0.20
    with:
      build_command: "mvn -B -V install -Dvalidate-format"
      upload_artifacts: true
